# Generated by Django 5.1.3 on 2024-12-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0015_remove_inscriptioncourse_certificat_med_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioncourse',
            name='invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscriptioncourse',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
